import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ur';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.templates': 'Templates',
    'nav.saas': 'SaaS',
    'nav.matrimonial': 'Wedding Cards',
    'nav.blog': 'Journal',
    'nav.about': 'About Maira',
    'nav.contact': 'Contact',
    'hero.tag1': 'Premium Digital Ecosystem',
    'hero.title1.serif': 'Elite SaaS &',
    'hero.title1.bold': 'Premium Apps.',
    'hero.desc1': 'High-performance SaaS applications and aesthetic digital systems. Precision-built for Template Forge innovators.',
    'hero.cta1': 'Explore SaaS',
    'hero.tag2': 'Expert Resource Vault',
    'hero.title2.serif': 'Pro Design',
    'hero.title2.bold': 'Digital Tools.',
    'hero.desc2': 'Hand-picked software and design ecosystems used to build and scale elite digital platforms with precision.',
    'hero.cta2': 'Explore Collection',
    'about.tag': 'Leadership & Global Vision',
    'about.title': 'The Vision of CEO Maira.',
    'about.desc': 'As the lead strategist and CEO behind Template Forge, I have dedicated my career to redefining digital elegance. Every resource here is a result of technical design and architectural refinement, specifically curated to provide the most sophisticated digital systems.',
    'about.feature1.title': "Maira's Strategic Intent",
    'about.feature1.desc': 'Every line of code and every pixel is personally vetted by me to ensure high-converting purpose and absolute technical superiority.',
    'about.feature2.title': 'Template Forge Standards',
    'about.feature2.desc': 'Fast, invisible, and efficient architecture designed for the 2026 digital era, powered by our custom performance protocols.',
    'ticker.title': 'Live Collection Viewer',
    'store.tag': 'Elite Collection',
    'store.title': 'The Digital Assets Library.',
    'cat.nav.tag': 'Market Exploration',
    'cat.nav.title': 'Strategic Categories.',
    'cat.nav.desc': 'Explore our curated collections designed for maximum conversion and aesthetic superiority.',
    'feedback.tag': 'Collaborative Innovation',
    'feedback.title': 'What Should We Forge Next?',
    'feedback.desc': "Tell us about the problems you face. Whether it's a specific SaaS tool you need or a design problem, Maira's team is ready to build the solution.",
    'feedback.submit': 'Submit Request',
    'footer.title': 'Future Innovation.',
    'footer.desc': 'Secure your access to our premium collections. Subscribe for early release notifications.',
    'cat.templates': 'Website Templates',
    'cat.templates.desc': 'Portfolio, Business & Landing Pages',
    'cat.nikkah': 'Nikkah Cards',
    'cat.nikkah.desc': 'Elegant Traditional Invitations',
    'cat.birthday': 'Birthday Cards',
    'cat.birthday.desc': 'Modern & Playful Greeting Designs',
    'aff.tag': 'Curated Tech Stack',
    'aff.title': 'The Elite',
    'aff.title.bold': 'Digital Arsenal',
    'aff.desc': 'We only recommend tools that we use to build high-performance digital experiences.',
    'aff.explore': 'Explore',
    'aff.starting': 'Starting At',
    'aff.stat1': 'Verified Tools',
    'aff.stat2': 'Global Users',
    'aff.stat3': 'Efficiency Boost',
    'aff.stat4': 'Tech Partners',
    'store.artisans': 'Exclusive Artisans',
    'store.avail': 'Available Now',
    'store.precision': 'Precision-built systems and aesthetic components for high-performance builders.',
    'prod.back': 'Back to Collection',
    'prod.license': 'Acquire License',
    'prod.docs': 'Technical Docs',
    'prod.access': 'Global Access',
    'prod.quality': 'Elite Quality',
    'prod.notfound': 'Asset Not Found',
    'prod.return': 'Return to Collection',
    'prod.architecture': '3D Architecture',
    'contact.tag': 'Connect With us',
    'contact.title1': "Let's build your",
    'contact.title2': 'Brand.',
    'contact.desc': "Have a project or a question? Send us a message and we'll help you get started.",
    'contact.name': 'Your Name',
    'contact.email': 'Email Address',
    'contact.category': 'Category',
    'contact.message': 'Message',
    'contact.placeholder.name': 'Name',
    'contact.placeholder.email': 'name@email.com',
    'contact.placeholder.msg': 'Tell us about your project...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success.title': 'Message Sent',
    'contact.success.desc': 'Thanks for reaching out. We will get back to you soon!',
    'contact.success.another': 'Send another message',
    'contact.opt1': 'Custom Web Design',
    'contact.opt2': 'Order Inquiries',
    'contact.opt3': 'Design Support',
    'contact.opt4': 'Collaboration',
    'blog.tag': 'Strategic Journal',
    'blog.title': 'Insights ',
    'blog.title.bold': '& Education.',
    'blog.desc': 'Master your craft with our latest tutorials. From mastering digital templates to building iconic SaaS systems for 2026.',
    'blog.read': 'Read Full Insights',
    'blog.all': 'Our Blog',
    'nav.login': 'Login',
    'nav.lang': 'Change Language',
    'footer.newsletter.success': 'Subscribed',
    'footer.newsletter.placeholder': 'Your Email Address',
    'footer.newsletter.btn': 'Join',
    'footer.nav.title': 'Navigation',
    'footer.connect.title': 'Connect',
    'footer.admin': 'Admin',
    'auth.login.title': 'Sign In',
    'auth.login.subtitle': 'Enter your details to access your account.',
    'auth.signup.title': 'Create Account',
    'auth.signup.subtitle': 'Join Forge to get premium templates.',
    'auth.forgot.title': 'Reset Password',
    'auth.forgot.subtitle': "We'll send a reset link to your email.",
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.login.btn': 'Sign In',
    'auth.signup.btn': 'Sign Up',
    'auth.forgot.btn': 'Send Link',
    'auth.google.btn': 'Continue with Google',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.forgotLink': 'Forgot Password?',
    'auth.backToLogin': 'Back to Login',
    'blog.detail.notfound': 'Article Not Found',
    'blog.detail.return': 'Return to Home',
    'blog.detail.back': 'Back to Strategic Journal',
    'blog.detail.author': 'Author',
    'blog.detail.readtime': 'Read Time',
    'blog.detail.share': 'Share Brief',
    'blog.detail.cta.title': 'Ready to implement this vision?',
    'blog.detail.cta.btn': 'Browse Collection',
    'hero.visual.protocol': 'System Active',
    'hero.visual.nexus': 'Network',
    'hero.visual.integrated': 'Integrated',
    'hero.visual.storefront': 'Store Front',
    'hero.visual.live': 'Live',
    'hero.visual.inventory': 'Inventory',
    'hero.visual.ordernexus': 'Orders Active',
    'cta.title': 'Get Premium ',
    'cta.title.bold': 'Asset Updates',
    'cta.title.end': ' & Early Access.',
    'store.templates.title': 'Digital Templates',
    'store.templates.subtitle': 'High-performance website architectures for portfolios, businesses, and landing pages.',
    'store.cards.title': 'Exclusive Cards',
    'store.cards.subtitle': 'Designer Nikkah and Birthday cards crafted for your most precious moments.',
    'cta.desc': 'Join 2,000+ creators and get notified the moment a new premium system drops. Elite resources, zero fluff.',
    'cta.placeholder': 'Enter your professional email',
    'cta.button': 'Subscribe',
    'benefits.tag': 'Our Benefits',
    'benefits.title': 'Why Choose ',
    'benefits.title.bold': 'Our Designs?',
    'benefit1.title': 'Easy to Edit',
    'benefit1.desc': 'Fully customizable layers and components using familiar tools.',
    'benefit2.title': 'Instant Download',
    'benefit2.desc': 'Access your files immediately after purchase. No waiting.',
    'benefit3.title': 'Beginner Friendly',
    'benefit3.desc': 'No coding or design degree required. Built for everyone.',
    'benefit4.title': 'High Aesthetic',
    'benefit4.desc': 'Engineered to stand out with elite design quality.'
  },
  ur: {
    'nav.home': 'ہوم',
    'nav.templates': 'ٹیمپلیٹس',
    'nav.saas': 'SaaS',
    'nav.matrimonial': 'نکاح کارڈز',
    'nav.blog': 'بلاگ',
    'nav.about': 'مائرہ کے بارے میں',
    'nav.contact': 'رابطہ',
    'hero.tag1': 'پریمیم ڈیجیٹل سسٹم',
    'hero.title1.serif': 'اعلیٰ SaaS اور',
    'hero.title1.bold': 'پریمیم ایپس۔',
    'hero.desc1': 'اعلیٰ کارکردگی والے SaaS ایپلی کیشنز اور خوبصورت ڈیجیٹل سسٹمز۔ مائرہ کے ذریعے ڈیزائن کردہ۔',
    'hero.cta1': 'ایکسپلور کریں',
    'hero.tag2': 'ماہرانہ وسائل کا خزانہ',
    'hero.title2.serif': 'پرو ڈیزائن',
    'hero.title2.bold': 'ڈیجیٹل ٹولز۔',
    'hero.desc2': 'اعلیٰ درجے کے ڈیجیٹل پلیٹ فارمز بنانے کے لیے منتخب کردہ سافٹ ویئر اور ڈیزائن ٹولز۔',
    'hero.cta2': 'کلکشن دیکھیں',
    'about.tag': 'قیادت اور عالمی وژن',
    'about.title': 'سی ای او مائرہ کا وژن۔',
    'about.desc': 'ٹیمپلیٹ فورج کے پیچھے لیڈ اسٹریٹجسٹ اور سی ای او کے طور پر، میں نے اپنے کیریئر کو ڈیجیٹل خوبصورتی کی ازسرنو تعریف کے لیے وقف کر دیا ہے۔ یہاں موجود ہر وسیلہ تکنیکی ڈیزائن اور فن تعمیر کا نتیجہ ہے، جو خاص طور پر جدید ترین ڈیجیٹل نظام فراہم کرنے کے لیے تیار کیا گیا ہے۔',
    'about.feature1.title': 'مائرہ کا تزویراتی ارادہ',
    'about.feature1.desc': 'کوڈ کی ہر لائن اور ہر پکسل کی میں نے ذاتی طور پر جانچ کی ہے تاکہ اعلیٰ معیار اور تکنیکی برتری کو یقینی بنایا جا سکے۔',
    'about.feature2.title': 'ایلیٹ ٹیمپلیٹ فورج معیار',
    'about.feature2.desc': 'تیز، پوشیدہ، اور موثر فن تعمیر جو 2026 کے ڈیجیٹل دور کے لیے ڈیزائن کیا گیا ہے۔',
    'ticker.title': 'لائیو کلکشن ویور',
    'store.tag': 'اعلیٰ کلکشن',
    'store.title': 'ڈیجیٹل اثاثوں کی لائبریری۔',
    'cat.nav.tag': 'مارکیٹ ایکسپلوریشن',
    'cat.nav.title': 'تزویراتی زمرے',
    'cat.nav.desc': 'زیادہ سے زیادہ تبادلوں اور جمالیاتی برتری کے لیے ڈیزائن کیے گئے ہمارے تیار کردہ مجموعوں کو دیکھیں۔',
    'feedback.tag': 'باہمی جدت',
    'feedback.title': 'ہمیں آگے کیا بنانا چاہیے؟',
    'feedback.desc': 'ہمیں ان مسائل کے بارے میں بتائیں جن کا آپ سامنا کر رہے ہیں۔ مائرہ کی ٹیم حل تیار کرنے کے لیے تیار ہے۔',
    'feedback.submit': 'درخواست جمع کرائیں',
    'footer.title': 'مستقبل کی جدت۔',
    'footer.desc': 'ہمارے پریمیم کلکشن تک رسائی حاصل کریں۔ نئی ریلیز کے لیے سبسکرائب کریں۔',
    'cat.templates': 'ویب سائٹ ٹیمپلیٹس',
    'cat.templates.desc': 'پورٹ فولیو اور بزنس پیجز',
    'cat.nikkah': 'نکاح کارڈز',
    'cat.nikkah.desc': 'خوبصورت روایتی ڈیزائن',
    'cat.birthday': 'سالگرہ کارڈز',
    'cat.birthday.desc': 'جدید اور خوبصورت ڈیزائن',
    'aff.tag': 'منتخب شدہ ٹیک اسٹیک',
    'aff.title': 'اعلیٰ',
    'aff.title.bold': 'ڈیجیٹل ہتھیار',
    'aff.desc': 'ہم صرف ان ٹولز کی سفارش کرتے ہیں جنہیں ہم اعلیٰ کارکردگی والے ڈیجیٹل تجربات بنانے کے لیے استعمال کرتے ہیں۔',
    'aff.explore': 'دیکھیں',
    'aff.starting': 'شروع ہو رہا ہے',
    'aff.stat1': 'تصدیق شدہ ٹولز',
    'aff.stat2': 'عالمی صارفین',
    'aff.stat3': 'کارکردگی میں اضافہ',
    'aff.stat4': 'ٹیک پارٹنرز',
    'store.artisans': 'خصوصی ڈیزائنز',
    'store.avail': 'ابھی دستیاب ہے',
    'store.precision': 'اعلیٰ کارکردگی والے بلڈرز کے لیے انتہائی درستگی کے ساتھ بنائے گئے نظام۔',
    'prod.back': 'کلکشن پر واپس جائیں',
    'prod.license': 'لائسنس حاصل کریں',
    'prod.docs': 'تکنیکی دستاویزات',
    'prod.access': 'عالمی رسائی',
    'prod.quality': 'اعلیٰ معیار',
    'prod.notfound': 'اثاثہ نہیں ملا',
    'prod.return': 'کلکشن پر واپس جائیں',
    'prod.architecture': '3D آرکیٹیکچر',
    'contact.tag': 'ہم سے رابطہ کریں',
    'contact.title1': 'آئیے آپ کا',
    'contact.title2': 'برانڈ بنائیں۔',
    'contact.desc': 'کوئی پراجیکٹ یا سوال ہے؟ ہمیں پیغام بھیجیں اور ہم آپ کی مدد کریں گے۔',
    'contact.name': 'آپ کا نام',
    'contact.email': 'ای میل ایڈریس',
    'contact.category': 'زمرہ',
    'contact.message': 'پیغام',
    'contact.placeholder.name': 'نام',
    'contact.placeholder.email': 'نام@ای میل',
    'contact.placeholder.msg': 'اپنے پراجیکٹ کے بارے میں بتائیں...',
    'contact.send': 'پیغام بھیجیں',
    'contact.sending': 'بھیج رہا ہے...',
    'contact.success.title': 'پیغام بھیج دیا گیا',
    'contact.success.desc': 'رابطہ کرنے کا شکریہ۔ ہم جلد ہی آپ سے رابطہ کریں گے!',
    'contact.success.another': 'دوسرا پیغام بھیجیں',
    'contact.opt1': 'کسٹم ویب ڈیزائن',
    'contact.opt2': 'آرڈر انکوائری',
    'contact.opt3': 'ڈیزائن سپورٹ',
    'contact.opt4': 'باہمی تعاون',
    'blog.tag': 'تزویراتی جرنل',
    'blog.title': 'بصیرت ',
    'blog.title.bold': 'اور تعلیم۔',
    'blog.desc': 'ہمارے تازہ ترین ٹیوٹوریلز کے ساتھ اپنے فن میں مہارت حاصل کریں۔ ڈیجیٹل ٹیمپلیٹس سے لے کر 2026 کے لیے SaaS سسٹمز بنانے تک۔',
    'blog.read': 'مکمل معلومات پڑھیں',
    'blog.all': 'ہمارا بلاگ',
    'nav.login': 'ممبر لاگ ان',
    'nav.lang': 'زبان تبدیل کریں',
    'footer.newsletter.success': 'آپ شامل ہو گئے ہیں',
    'footer.newsletter.placeholder': 'ای میل درج کریں',
    'footer.newsletter.btn': 'شامل ہوں',
    'footer.nav.title': 'نیویگیشن',
    'footer.connect.title': 'روابط',
    'footer.admin': 'ایڈمن',
    'auth.login.title': 'سائن ان کریں',
    'auth.login.subtitle': 'اپنے اکاؤنٹ تک رسائی حاصل کرنے کے لیے اپنی تفصیلات درج کریں۔',
    'auth.signup.title': 'اکاؤنٹ بنائیں',
    'auth.signup.subtitle': 'پریمیم ٹیمپلیٹس حاصل کرنے کے لیے ہمارے ساتھ شامل ہوں۔',
    'auth.forgot.title': 'پاس ورڈ ری سیٹ کریں',
    'auth.forgot.subtitle': 'اپنا پاس ورڈ دوبارہ حاصل کرنے کے لیے لنک حاصل کریں۔',
    'auth.email': 'ای میل ایڈریس',
    'auth.password': 'پاس ورڈ',
    'auth.confirmPassword': 'پاس ورڈ کی تصدیق کریں',
    'auth.login.btn': 'سائن ان کریں',
    'auth.signup.btn': 'سائن اپ کریں',
    'auth.forgot.btn': 'ری سیٹ لنک بھیجیں',
    'auth.google.btn': 'گوگل کے ساتھ سائن ان کریں',
    'auth.noAccount': 'اکاؤنٹ نہیں ہے؟',
    'auth.hasAccount': 'پہلے سے اکاؤنٹ ہے؟',
    'auth.forgotLink': 'پاس ورڈ بھول گئے؟',
    'auth.backToLogin': 'سائن ان پر واپس جائیں',
    'blog.detail.notfound': 'مضمون نہیں ملا',
    'blog.detail.return': 'ہوم پیج پر واپس جائیں',
    'blog.detail.back': 'اسٹریٹجک جرنل پر واپس جائیں',
    'blog.detail.author': 'مصنف',
    'blog.detail.readtime': 'پڑھنے کا وقت',
    'blog.detail.share': 'شیئر کریں',
    'blog.detail.cta.title': 'کیا آپ اس وژن کو نافذ کرنے کے لیے تیار ہیں؟',
    'blog.detail.cta.btn': 'کلکشن دیکھیں',
    'hero.visual.protocol': 'سسٹم فعال ہے',
    'hero.visual.nexus': 'نیٹ ورک',
    'hero.visual.integrated': 'ٹیم',
    'hero.visual.storefront': 'اسٹور فرنٹ',
    'hero.visual.live': 'لائیو',
    'hero.visual.inventory': 'اسٹاک',
    'hero.visual.ordernexus': 'آرڈرز فعال ہیں',
    'cta.title': 'پریمیم ',
    'cta.title.bold': 'اپ ڈیٹس حاصل کریں',
    'cta.title.end': ' اور رسائی حاصل کریں۔',
    'store.templates.title': 'ڈیجیٹل ٹیمپلیٹس',
    'store.templates.subtitle': 'پورٹ فولیوز اور کاروبار کے لیے اعلیٰ کارکردگی والے ویب سائٹ ڈیزائن۔',
    'store.cards.title': 'خصوصی کارڈز',
    'store.cards.subtitle': 'آپ کے قیمتی لمحات کے لیے ڈیزائن کردہ نکاح اور سالگرہ کے کارڈز۔',
    'cta.desc': '2000 سے زائد تخلیق کاروں میں شامل ہوں اور پریمیم سسٹم کی ریلیز کی اطلاع پائیں۔',
    'cta.placeholder': 'اپنی ای میل درج کریں',
    'cta.button': 'سبسکرائب کریں',
    'benefits.tag': 'ہمارے فوائد',
    'benefits.title': 'ہمارے ڈیزائن ',
    'benefits.title.bold': 'کیوں منتخب کریں؟',
    'benefit1.title': 'تبدیلی میں آسان',
    'benefit1.desc': 'کینوا یا فگما جیسے ٹولز کے ذریعے آسانی سے تبدیلی کریں ڈیزائنز میں۔',
    'benefit2.title': 'فوری ڈاؤن لوڈ',
    'benefit2.desc': 'خریداری کے فوراً بعد اپنی فائلز تک رسائی حاصل کریں۔',
    'benefit3.title': 'آسان استعمال',
    'benefit3.desc': 'کسی کوڈنگ یا ڈگری کی ضرورت نہیں۔ سب کے لیے ڈیزائن کیا گیا۔',
    'benefit4.title': 'اعلیٰ جمالیات',
    'benefit4.desc': 'جدید برانڈز کے لیے ایلیٹ ڈیزائن جو آپ کو نمایاں کرے۔'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
